In [1]:
import numpy as np

In [2]:
print(np.array([1, 2, 3]))  #printing the array 

[1 2 3]


In [10]:
#taking the 2d array and print
myarr=np.array([[1,3,4],[4,5,3]])
myarr

array([[1, 3, 4],
       [4, 5, 3]])

In [11]:
#showing the shape
myarr.shape


(2, 3)

In [13]:
#accessing the elements by row and column as both indexs start from 0 AND 1
myarr[1,1]

5

In [14]:
#Taking 3d arrays as well
myarr=np.array([[1,2,3],[1,323,3],[234,33,222]])
myarr

array([[  1,   2,   3],
       [  1, 323,   3],
       [234,  33, 222]])

In [15]:
#creating the array with equal length and same width
np.linspace(1,5,4)#1 is the first element and 5 is the last elemengts and 4 is the WIDTH

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [19]:
#Creating random array
emp=np.empty((2,2))
emp

array([[1.        , 2.33333333],
       [3.66666667, 5.        ]])

In [21]:
#generating an array of range x
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
#if we want to rearrange then
re=arr.reshape(3, 33)
re

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [25]:
#adding sum of rows and colums
'''too add rows then axis=1
too add columns axis=0
'''
x=[[1,3,2],[22,4,2],[2,4,44]]
arr=np.array(x)
arr


array([[ 1,  3,  2],
       [22,  4,  2],
       [ 2,  4, 44]])

In [26]:
arr.sum(axis=0)#columns

array([25, 11, 48])

In [27]:
arr.sum(axis=1)#rows

array([ 6, 28, 50])

In [28]:
#creating transpose of a matrix 
arr.T


array([[ 1, 22,  2],
       [ 3,  4,  4],
       [ 2,  2, 44]])

In [29]:
#finding the max and min in a arayy
arr.max()

44

In [30]:
#addind and multiplication of two matrices
ar=np.array([[1,3,4],[3,2,4],[34,44,22]])
ar

array([[ 1,  3,  4],
       [ 3,  2,  4],
       [34, 44, 22]])

In [31]:
ar+arr

array([[ 2,  6,  6],
       [25,  6,  6],
       [36, 48, 66]])

In [32]:
#multiplication
ar*arr

array([[  1,   9,   8],
       [ 66,   8,   8],
       [ 68, 176, 968]])

In [34]:
#findind the sqrt of the mTRIX
np.sqrt(ar)

array([[1.        , 1.73205081, 2.        ],
       [1.73205081, 1.41421356, 2.        ],
       [5.83095189, 6.63324958, 4.69041576]])